
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: weatherapp-envs
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: http://gitlab/new-username/weatherapp-deploy.git
        revision: main
        directories:
          - path: weatherapp-chart/environments/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: http://gitlab/new-username/weatherapp-deploy.git
        targetRevision: main
        path: weatherapp-chart
        helm:
          valueFiles:
            - environments/{{path.basename}}/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - Prune=true

