apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weatherapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: http://new-username:glpat-zU7WbLHysxabRz4tRfyn@hadarapp.com/gitlab/new-username/weatherapp-deploy.git
    targetRevision: main
    path: weatherapp-chart
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: deployapp
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

